### ISSUE TITLE
Doesn't work in 1.4

### ISSUE THREAD

**Issue by nobodyinteresting** [XT-0xFF/CustomizeAnimals#3]
Understandably, this mod is broken with the release of 1.4. Are there any plans to update? This is one of my favorite mods, and while I can play without it, being able to edit anything about any animal sure makes games more fun.

If you need logs or whatever I can get 'em.

**Comment by nobodyinteresting** [comment]
Closing this as there was a 1.4 update today. Hooray!

**Comment by ChrisF-127** [comment]
They changed Toxic Sensitivity into Toxic Resistance, which caused a crash, otherwise the mod seems to work fine in 1.4 without changes.
Maybe I should try and catch such issues, but then again, they shouldn't happen either way.

Hopefully that's all, I just checked if it compiles and runs fine, please report any further issues!
