### ISSUE TITLE
Bug: ContentFinder patch seems to be applying to more than expected

### ISSUE THREAD

**Issue by Caaz** [XT-0xFF/CustomizeAnimals#4]
Hi there! It appears your [patch here](https://github.com/XT-0xFF/CustomizeAnimals/blob/master/Source/CustomizeAnimals/Main/HarmonyPatches.cs#L28-L30) is patching more than expected. https://github.com/Music-Expanded/music-expanded-framework/issues/45

# Steps to Replicate
Load CustomizeAnimals + Music Expanded Core + Music Expanded Framework, this should cause the error to pop up on load.

# Thoughts
So in MEF when a theme is selected, and when the menu loads, we call `ResolveReferences` on SoundDefs to reload audio grains (for themes that switch sounds around). Normally this happens before mod loading I suppose, so that explains why you may've not noticed it happen for any of the vanilla sounddefs. 

I figure the intent here is that textures get loaded when a thing spawns, and so the patch catches it, but it assumes all things that the patch handles are Texture2Ds.

I'm really not sure how to solve for this one 🤔 If you've got an idea of how I could swap out sounds without Resolving References I could do that, but I think a better approach would be to limit this patch.

# Stacktrace
```
Could not load UnityEngine.Texture2D at MusicExpanded/Medieval/Medieval_Fantasy_Quest_Complete in any active mod or in base resources.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
(wrapper dynamic-method) Verse.ContentFinder`1<UnityEngine.Texture2D>:Verse.ContentFinder`1[[UnityEngine.Texture2D, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].Get_Patch1 (string,bool)
Verse.Sound.AudioGrain_Clip/<GetResolvedGrains>d__1:MoveNext ()
Verse.Sound.SubSoundDef:<ResolveReferences>b__33_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:ExecuteWhenFinished (System.Action)
Verse.Sound.SubSoundDef:ResolveReferences ()
Verse.SoundDef:ResolveReferences ()
MusicExpanded.ThemeDef:ResolveSounds (MusicExpanded.ThemeDef)
MusicExpanded.Patches.MusicManagerEntry/StartPlaying:Prefix (RimWorld.MusicManagerEntry)
(wrapper dynamic-method) RimWorld.MusicManagerEntry:RimWorld.MusicManagerEntry.StartPlaying_Patch1 (RimWorld.MusicManagerEntry)
RimWorld.MusicManagerEntry:MusicManagerEntryUpdate ()
Verse.Root_Entry:Update ()
```

**Comment by ChrisF-127** [comment]
What a strange error. 
I was always a bit worried that patch might have side effects, but not in this way.

I don't yet understand how this patch causes the game to attempt to load the AudioClip as a Texture2D object, because the error is technically speaking not caused in the patch. Will need to test around a bit and read up on patching generics to figure out what happens here and how to fix it. 

All that patch is supposed to do is add a "pack"-texture for animals missing them, when enabling "pack animal". Always considered it a bit of a dirty patch, but at the time I had no idea how else to do it, I guess.

**Comment by ChrisF-127** [comment]
Alright, I've changed that PostFix patch to be applied via a Transpiler for Graphic_Multi.Init instead in version 1.4.3.
Hopefully it still catches all cases where the pack-animal texture is loaded, from my quick testing it worked fine.

The error should be fixed though, due to avoiding touching ContentFinder itself.
Thank you for finding this problem!
